http:
  port: 3005
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/api'
  user:
    host: localhost
    paths: ["/user", "/user/*"]
  class:
    host: localhost
    paths: ["/class", "/class/*"]
serviceEndpoints:
  apiService:
    url: 'http://localhost:3000'
  userService:
    url: "http://localhost:3001"
  classService:
    url: "http://localhost:4000"
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
    # add thr parameter oauth2 to activate the oauth.
      - oauth2:
      - proxy:
          - action:
              serviceEndpoint: apiService
              changeOrigin: true
  userPipeline:
    apiEndpoints:
      - user
    policies:
      - proxy:
          - action:
               serviceEndpoint: userService
               changeOrigin: true
  classPipeline:
    apiEndpoints:
       - class
    policies:
      - proxy:
          - action:
               serviceEndpoint: classService
               changeOrigin: true   
